import type { NextPage } from "next";
import Head from "next/head";
import { PageTemplate, Search, Dish } from "@/components";
import Styles from "../styles/internal.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>onFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        <div className={Styles.content}>
          <h1>Encontre as opções de delivery próximas a você.</h1>
          <Search />
          <h2>
            Descubra seu novo Delivery favorito. Milhares de opções a um clique.
          </h2>
        </div>
      </PageTemplate>
    </>
  );
};

export default Home;
